config/routes.rb
Rails.application.routes.draw do

  get    'signin'   => 'sessions#new'
  post   'signin'   => 'sessions#create'
  delete 'signout'  => 'sessions#destroy'
  resources :users
  resources :posts, only: [:new, :create, :index]

  root 'users#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  before_create :remember
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    Digest::SHA1.hexdigest(string)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.digest(User.new_token)
    self.remember_digest = remember_token
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create]

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "post successfully created"
      redirect_to root_url
    else
      render :new
    end
  end

# Confirms a signed-in user.
  def signed_in_user
    unless signed_in?
      #store_location
      flash[:danger] = "Please sign in."
      redirect_to signin_url
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      #session[:user_id] = user.id
      sign_in(user)
      remember user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if signed_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
  end

  def show
  end

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<header>
<% if signed_in? %>
  <%= link_to "Sign out", signout_path, method: "delete" %>
  <%= link_to "Create post", new_post_path %>
  <p><%= current_user.name %></p>
<% else %>
  <%= link_to "Sign in", signin_path %>
<% end %>
<%= link_to "All posts", posts_path %>
</header>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1> All Posts </h1>

<ul class="users">

<% @posts.each do |post| %>
    <li>
      <p>Title: <%= post.title %></p>
      <p>Body: <%= post.body %></p>
      <% if signed_in? %>
      <p>Author: <%= User.find_by(id: post.user_id).name %></p>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

  <div">
    <%= form_for @post do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :body %>
      <%= f.text_field :body %>

      <%= f.submit "Create post" %>
    <% end %>

  </div>

app/views/users/home.html.erb
<h1>Welcome to the Members Only App</h1>

app/views/users/show.html.erb
<h1>You've just signed in</h1>